### ISSUE TITLE
The memory utilization is increasing in Istanbul BFT (Version: 21.1.0)

### ISSUE THREAD

**Issue by sokiaoba** [ConsenSys/quorum#1259]
#### System information

Quorum Version: 21.1.0

#### Expected behaviour

The memory utilization is periodically released.

#### Actual behaviour

The memory utilization is increasing.

#### Steps to reproduce the behaviour

I run Quorum network on AKS, using a folk of https://github.com/ConsenSys/quorum-azure.
The folk repository is [here](https://github.com/GincoInc/quorum-azure/).

Setup is basically same as [the original](https://github.com/ConsenSys/quorum-azure#usage).
(I use Argocd to install charts but I suppose it doesn't make any changes)

#### Backtrace

<img width="1421" alt="Screen Shot 2021-09-24 at 16 26 24" src="https://user-images.githubusercontent.com/1026591/134635295-1a1ee356-272a-450e-ab10-5ebbef401df5.png">

Thank you.

**Comment by ricardolyn** [comment]
thanks @sokiaoba . we will investigate this and provide a feedback based on what we find.

**Comment by sokiaoba** [comment]
Hello.  

I experimented to see what will happen if the memory consumption reaches to the limit. 
(I set the memory limit to 600MB)

And here is what I found.

![135553879-c982e421-0cbb-4762-9de5-fcc2bdcfa83b](https://user-images.githubusercontent.com/1026591/135583137-967c0638-a2d0-4a71-b9cf-a75ec7110d5c.png)

1. memory comsumption increases and reaches to the limit 
2. the node shutdowns
3. the node restarts and the memory comsumption reset a bit
4. back to 1 

And it seems the more the node restarts, the amount of reset of memory comsumption becomes less.
(Which means the cycle of the loop above becomes shorter & shorter, I guess)

I hope you'll give us a feedback.

**Comment by sokiaoba** [comment]
As I expected, as the time passes, a period of the cycle (pod restart -> memory comsumption increase -> OOMKilled) became shorter & shorter, and eventually the pod ends up in CrashLoopBackOff. I think it's critical.

![memory usage](https://user-images.githubusercontent.com/1026591/135784749-52a1d697-787d-4fec-a86e-9cc0a0a3d8e5.png)

Could you investigate it? @ricardolyn

**Comment by ricardolyn** [comment]
let's limit at 3 days after the Azure access is given

**Comment by baptiste-b-pegasys** [comment]
Hello, I reproduced the memory increase and done some memory profiling.

The most significant one is about levelDB memory, used in the trie cache.
It's a cache optimisation in order to improve (make less) writes when a block is validated.

Also a large memory is allocated also for another cache, that you may not need and want to reduce as well.

Both are related to go-ethereum performance tuning options (geth help) 
Some are a percentage of the database size.
I suggest to reduce the percentage of them.

From the code, I can see the memory can be flushed after at least 128 blocks and there is a flush when it exceeds the memory cache (TrieDirtyLimit, default 256MB) or after a timeout (TrieTimeLimit, default 1 hour).

All the trie cache can be disabled when it runs as an archive mode. (`gcmode="archive"`)

In the TOML config file, you can set the time out in the config section with : `TrieTimeout: 5m` (go duration) and less memory 
For the trie memory cache limit, in the code it's calculated: `cache.TrieDirtyLimit = ctx.GlobalInt(CacheFlag.Name) * ctx.GlobalInt(CacheGCFlag.Name) / 100`

`cache` is 1024MB by default, and `cache.gc` is 25 %, so 256MB.

So you may try to reduce either `cache` or `cache.gc`.

In the screenshot, I highlighted the main increase found after running around a day:
![image.png](https://images.zenhubusercontent.com/60b5f33a5f7d3741930b21e9/9acc43af-6ddd-4f4d-a88f-9a3615b3f462)

The two big ones on top are allocated at start, and may be reducable with the performance tuning as well if you want.

**Comment by sokiaoba** [comment]
Thank you. I'll try option tuning and give you feedback.

**Comment by baptiste-b-pegasys** [comment]
Feel free to reopen the ticket if you encounter the issue again.
