### ISSUE TITLE
Metrics Data issue : Incorrect P2P metric values

### ISSUE THREAD

**Issue by rushikeshacharya** [ConsenSys/quorum#1581]
#### System information

Geth version: 1.9.24-stable
OS & Version: Windows/Linux
Quorum Version: 22.7.3

#### Expected behaviour

The P2P_Peers metric for quorum nodes should have a co-relation with net.PeerCount value.

#### Actual behaviour

P2P_Peer Count is always higher than twice the value of net.PeerCount.

#### Steps to reproduce the behaviour

Net Peer Count result
```
net.peerCount
9
```

![net peerCount](https://user-images.githubusercontent.com/18182040/206139066-513c0e53-68cf-4a92-8ba4-1199d4f3f36c.png)

p2p_peers metrics result
```
 curl -sS http://localhost:metricsport/debug/metrics/prometheus | grep "p2p_peers" -i
# TYPE p2p_peers gauge
p2p_peers 13
```
I'm getting the different p2p_peer values every time I execute above command.  Please find the attached screenshots for the same.

![p2p_peers](https://user-images.githubusercontent.com/18182040/206138610-61077d2a-2322-4828-8c02-8571af2e6a84.png)

I've tried to setup [quorum-kubernetes](https://github.com/ConsenSys/quorum-kubernetes) env locally and there I'm getting the correct quorum count value from p2p_peers metrics.
 
Also is there a document depicting different metrics & its details available on Quorum.

**Comment by Krish1979** [comment]
The metrics is derived from the below code 

 

"activePeerGauge     = metrics.NewRegisteredGauge("p2p/peers", nil)"



which is incremented when a P2P TCP connection is established and it is decremented when a connection is closed. At the time when this counter is incremented the RLPx connection is not fully established - in fact the RLPx is only just starting. It may happen that during the RLPx negotiation the newly created connection is identified as a duplicate and closed. However - if you invoke the metrics service between the `inc` and `dec` events - you are likely to get a value above the one you are expecting. That explains why you are roughly seeing double the peer count in most cases. 



Furthermore, if your network setup introduces any delay for the TCP connection closing (maybe the VPN does that or even have orphan connections), the likelihood for you to observe such a behaviour is further increased. 


So this is expected behaviour and not an issue.
